#!/bin/sh

TOP_DIR="$(dirname "$0")"
BIN_DIR="$TOP_DIR"/src/main/dist/bin

gvim \
	"$TOP_DIR"/pom.xml "$TOP_DIR"/edit-sources* \
	"$TOP_DIR"/test "$TOP_DIR"/test.bat \
	"$BIN_DIR"/* \
    	"$TOP_DIR"/src/main/java/com/alteredmechanism/notepad/*.java
