#!/bin/sh

# Dev install under UNIX and UNIX-like systems
# Maybe this should be done with the Maven Ant plugin?

# Steps:
# 1. Build, if necessary
# 2. Unzip dist zip
# 3. Run dist install script

DIST_ZIP=target/rune-1.0-bin.zip
EXTRACT_DIR=target/rune-1.0

if [ ! -f "$DIST_ZIP" ]
then
  ./mvnw package || exit
fi

unzip -o "$DIST_ZIP" -d target

"$EXTRACT_DIR"/bin/install
