#!/bin/sh

VENDOR_PREFIX=alteredmechanism
APP_NAME=Rune
START_SCRIPT="$1"
ICON=rune.png

cleanup()
{
  if [ -f "$DESKTOP_TMP" ]
  then
    rm "$DESKTOP_TMP"
    rmdir "$(dirname "$DESKTOP_TMP")" 
  fi
}

# Creates a temporary directory in the system temp directory with
# a unique name.
# $1 - The name of this script
# $2 - Purpose of the temporary directory
# Output - The name of the temp directory that was created
makeTempDir()
( # Parentheses create subshell which makes all variables local.
  TRUE=0
  FALSE=1
  MAX_TRY_COUNT=20

  scriptName=`basename "$1"`
  purpose="$2"
  sysTempDir="${TMPDIR:-/tmp}"
  foundAvailableName=$FALSE
  tryCount=0
  unset tempDir

  while [ "$foundAvailableName" -eq "$FALSE" ] && [ "$tryCount" -lt "$MAX_TRY_COUNT" ]
  do
    dateToSeconds=`date +%Y%m%d%H%M%S`
    tempDir="$sysTempDir"/"$scriptName"."$purpose".$$."$dateToSeconds"
    if stat "$tempDir" 2> /dev/null
    then
      # Directory already exists, skip it
      tryCount=`expr "$tryCount" + 1`
    else
      # File does not exist
      mkdir "$tempDir" || exit
      foundAvailableName=$TRUE
    fi
  done
  echo "$tempDir"
)

# A temp directory is needed as opposed to a temp file
# because the temp name that will be created will not be the kind
# of name that is needed. The vendor prefix is required.
TEMP_DIR=`makeTempDir "$0" "desktop-file"`
if [ -z "$TEMP_DIR" ]
then
  echo Failed to create temp dir 1>&2
  exit 1
fi
DESKTOP_FILE="$TEMP_DIR"/"$VENDOR_PREFIX"-"$APP_NAME".desktop

cat <<EOF >"$DESKTOP_FILE"
[Desktop Entry]
Name=$APP_NAME
Exec=$START_SCRIPT
Type=Application
StartupNotify=true
Terminal=false
Comment=A multi-tab, themeable, text editor
Path=$HOME
Categories=Development,Utility
Encoding=UTF-8
Icon=$ICON
# List of valid categories:
# https://specifications.freedesktop.org/menu-spec/latest/apa.html
EOF

xdg-desktop-menu install "$DESKTOP_FILE"
cleanup

